#!/home/action/python3/bin/python 

import redis
import sys

r = redis.Redis("localhost")

#r.publish(sys.argv[1],"["+sys.argv[2]+"] " + " ".join(sys.argv[3:]))

#r.publish(sys.argv[1],sys.argv[2]) 
chan ="herc"
#data = "stuff"
data = [0,1,3,'key01','the data for cyl=0, hd=1,r=3']
print("sending to channel '%s'  data: '%s' " % (chan,data))
r.publish(chan,data) 