#!/usr/bin/python 

import ckdutil
from ckdutil import *

def hexStr(nm,ar):
    print("---- (hexStr)---" + nm)
    s = ""
    for c in ar:
        #print(c)
        s+= str(c)
    print("s: " + s)
    return s

def test1(ck):
    print("------ test1 - (create dasd, write two recs)")
    print("Seek")
    r =ck.seek(0,1)
    print("write")

    ks    = hexStr("ks",[0xF0,0xF1,0xF1])
    data  = hexStr("data",[0xC1,0xC2,0xC3])

    #ck.write(cyl,hd,rec,ks,data,True)
    ck.write(0,1,1,ks,data,True)

    ks    = hexStr("ks",[0xF0,0xF1,0xF2])
    data  = hexStr("data",[0xC4,0xC5,0xC6])
    ck.write(0,1,2,ks,data,True)

def test3(ck):
    print("------ test3 - (add records to existing dasd )")
    print("Seek")
    r =ck.seek(0,1)
    print("write")

    ks    = hexStr("ks",[0xF0,0xF1,0xF3])
    data  = hexStr("data",[0xC7,0xC8,0xC9])

    #ck.write(cyl,hd,rec,ks,data,True)
    ck.write(0,1,3,ks,data,True)

    ks    = hexStr("ks",[0xF0,0xF1,0xF4])
    data  = hexStr("data",[0xD1,0xD2,0xD3])
    ck.write(0,1,4,ks,data,True)


def read(ck,rn):
    rec = ck.read(rn)
    print("rec#: %d" % rn)
    print(rec)

def test2(ck):
    print("\n\n\n--------- test2 : read from existing DASD")
    print("-- Attach --")

    print("-- Seek ---")
    ck.seek(0,1)

    print("read")
    read(ck,1)
    read(ck,2)
    read(ck,3)
    read(ck,4)

ck = {}

fname  = 'dasd/t2305'
device = '2305'

#print("New ..")

ck = ckd.new(fname,device,None,False,True)

#ck.detach()
#ck = ckd.attach(fname,False)  # False ReadOnly

test1(ck)
#test3(ck)
test2(ck)

ck.detach(True)


# 1 - new, detach, attach, write, read   WORKS
# 2  - new, (noDetach), write, read    WORKS